name: 'Intel ICPX Build'

# Trigger on a push to the 'intel_icpx' branch
on:
  push:
    branches:
      - intel_icpx

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  Setup:
    runs-on: [self-hosted, icpx]
    if: github.actor == 'laurilaatu' || github.actor == 'alexanderrichards' || github.actor == 'EdAtkin' || github.actor == 'alisanikiforova'
    steps:
      - name: Cleanup Workspace
        run: rm -rf $GITHUB_WORKSPACE/*
      - name: Check out MaCh3 Core
        uses: actions/checkout@v6
        with:
          path: MaCh3Core
      - name: Check out MaCh3Tutorial
        uses: actions/checkout@v6
        with:
          repository: mach3-software/MaCh3Tutorial
          ref: intel_icpx
          path: MaCh3Tutorial
      - name: Check out MaCh3Utils
        uses: actions/checkout@v6
        with:
          repository: alexanderrichards/MaCh3Utils
          path: MaCh3Utils

  Build:
    needs: Setup
    runs-on: [self-hosted, icpx]
    strategy:
      matrix: &build-matrix
        build-type: [ "cpu", "emulator", "hardware" ]
      fail-fast: false
    steps:
      - name: Build MaCh3Core
        run: MaCh3Utils/start_build.sh ${{ matrix.build-type }} MaCh3Core build_${{ matrix.build-type }}
      - name: Build MaCh3Tutorial
        run: |
          source $GITHUB_WORKSPACE/MaCh3Core/build_${{ matrix.build-type }}/bin/setup.MaCh3.sh
          MaCh3Utils/start_build.sh ${{ matrix.build-type }} MaCh3Tutorial build_${{ matrix.build-type }}

  Validate:
    needs: Build
    runs-on: [self-hosted, icpx]
    strategy:
      matrix: &build-matrix
        build-type: [ "cpu", "emulator", "hardware" ]
      fail-fast: false
    steps:
      - name: Run Validation
        run: MaCh3Utils/run_tests.sh MaCh3Core/build_${{ matrix.build-type }} MaCh3Tutorial/build_${{ matrix.build-type }}
      - name: Create Runtime Summary
        run: echo ":clock10:" `grep elapsed MaCh3Tutorial/build_${{ matrix.build-type }}/out.txt` >> $GITHUB_STEP_SUMMARY

  Archive:
    needs: Validate
    runs-on: [self-hosted, icpx]
    env:
      ARCHIVE_DIR: /home/hep/llaatu/mach3/output
    strategy:
      matrix: &build-matrix
        build-type: [ "cpu", "emulator", "hardware" ]
      fail-fast: false
    steps:
      - name: Create Re-usable Timestamp
        run: |
          TIMESTAMP=$(date +%s)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV
      - name: Archive Output
        run: cp MaCh3Tutorial/build_${{ matrix.build-type }}/out.txt $ARCHIVE_DIR/out_${{ matrix.build-type }}_$TIMESTAMP.txt
      - name: Archive Hardware Runtime
        if: matrix.build-type == 'hardware'
        run: echo $TIMESTAMP `grep elapsed MaCh3Tutorial/build_${{ matrix.build-type }}/out.txt` >> $ARCHIVE_DIR/runtimes
      - name: Archive Hardware Report
        if: matrix.build-type == 'hardware'
        run: zip -r $ARCHIVE_DIR/reports/report_${{ matrix.build-type }}_$TIMESTAMP MaCh3Core/build_${{ matrix.build-type }}/splines/libSplines.so.prj/reports
      - name: Upload Report Artifact
        if: matrix.build-type == 'hardware'
        uses: actions/upload-artifact@v4
        with:
          name: fpga-build-report
          overwrite: true
          path: ${{ env.ARCHIVE_DIR }}/reports/report_${{ matrix.build-type }}_${{ env.TIMESTAMP }}.zip
