name: 'Intel ICPX Build'

# Trigger on a push to the 'intel_icpx' branch
on:
  push:
    branches:
      - intel_icpx

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  Setup:
    runs-on: [self-hosted, icpx]
    if: github.actor == 'laurilaatu' || github.actor == 'alexanderrichards' || github.actor == 'EdAtkin'
    steps:
      - name: Cleanup Workspace
        run: rm -rf $GITHUB_WORKSPACE/*
      - name: Check out MaCh3 Core
        uses: actions/checkout@v6
        with:
          path: MaCh3Core
      - name: Check out MaCh3Tutorial
        uses: actions/checkout@v6
        with:
          repository: mach3-software/MaCh3Tutorial
          ref: intel_icpx
          path: MaCh3Tutorial
      - name: Check out MaCh3Utils
        uses: actions/checkout@v6
        with:
          repository: alexanderrichards/MaCh3Utils
          path: MaCh3Utils

  Build:
    needs: Setup
    runs-on: [self-hosted, icpx]
    strategy:
      matrix: &build-matrix
        build-type: [ "cpu", "emulator", "hardware" ]
      fail-fast: false
    steps:
      - name: Build MaCh3Core
        run: MaCh3Utils/start_build.sh ${{ matrix.build-type }} MaCh3Core build_${{ matrix.build-type }}
      - name: Build MaCh3Tutorial
        run: |
          source $GITHUB_WORKSPACE/MaCh3Core/build_${{ matrix.build-type }}/bin/setup.MaCh3.sh
          MaCh3Utils/start_build.sh ${{ matrix.build-type }} MaCh3Tutorial build_${{ matrix.build-type }}

  Validate:
    needs: Build
    runs-on: [self-hosted, icpx]
    strategy:
      matrix: &build-matrix
        build-type: [ "cpu", "emulator", "hardware" ]
      fail-fast: false
    steps:
      - name: Run Validation
        run: |
          MaCh3Utils/run_tests.sh MaCh3Core/build_${{ matrix.build-type }} MaCh3Tutorial/build_${{ matrix.build-type }}
          runtime=$(date +%s)
          echo ":clock10: `grep elapsed MaCh3Tutorial/build_${{ matrix.build-type }}/out.txt`" >> $GITHUB_STEP_SUMMARY
          #cp ./out.txt $GITHUB_WORKSPACE/MaCh3Tutorial/build_${{ matrix.build-type }}/out_${{ matrix.build-type }}_$runtime.txt
